export enum RepositoryEnum {
    PRODUCT_REPOSITORY = "PRODUCT_REPOSITORY",
    CATEGORY_REPOSITORY = "CATEGORY_REPOSITORY",
    AUTHOR_REPOSITORY = "AUTHOR_REPOSITORY",
    BOOK_REPOSITORY = "BOOK_REPOSITORY",
}

